name: Publica√ß√£o autom√°tica
on: [workflow_dispatch]
  # nosso script ser√° executado sempre quando houver push e pull request nas branches destacadas abaixo
  #push:
    #branches: [ "main" ]
  #pull_request:
   #branches: [ "main" ]
jobs:
  build:
    # sistema operacional da m√°quina que o Github ir√° disponibilizar para rodar o nosso script
    runs-on: ubuntu-latest

    # aqui √© iniciado o passo a passo para realizar o processo de publica√ß√£o
    steps:
      - uses: actions/checkout@v3

      - name: Cria um arquivo tempor√°rio para a chave privada 
        run: |
               echo "${{ secrets.KEY }}" > /tmp/private_key
               chmod 600 /tmp/private_key

      - name: Criando a pasta da aplica√ß√£o e acertando diret√≥rio...
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo mkdir -p /home/ubuntu/appdemo1 

      - name: Ajustar permiss√µes no servidor de Produ√ß√£o
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} "sudo chown -R ubuntu:ubuntu /home/ubuntu/appdemo1 && sudo chmod -R 755 /home/ubuntu/appdemo1"
                     
      - name: Transferindo os arquivos da aplica√ß√£o
        run: |
               scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${{ github.workspace }}/* ubuntu@${{ secrets.HOST }}:/home/ubuntu/appdemo1

      - name: Restaurando a aplica√ß√£o
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo npm install --prefix /home/ubuntu/appdemo1 \

      - name: Reiniciando o PM2
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               pm2 restart app --update-env               

      - name: Limpa o arquivo de chave privada ap√≥s uso
        run: |
           rm /tmp/private_key
           
      - name: Notificar Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"üöÄ Deploy realizado com sucesso no reposit√≥rio **${{ github.repository }}** na branch **${{ github.ref_name }}**"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
